### ISSUE TITLE
brew install fails when using `--with-input-method`

### ISSUE THREAD

**Issue by beeender** [xcodebuild/fcitx-remote-for-osx#11]
When install it with 

``` bash
brew install fcitx-remote-for-osx --with-input-method=sogou-pinyin
```

it always fails with

```
=> Downloading https://github.com/CodeFalling/fcitx-remote-for-osx/archive/0.1.
Already downloaded: /Library/Caches/Homebrew/fcitx-remote-for-osx-0.1.0.tar.gz
==> ./build.py build
Last 15 lines from /Users/cc/Library/Logs/Homebrew/fcitx-remote-for-osx/01.build.py:
2016-05-17 16:14:01 +0800

./build.py
build


Traceback (most recent call last):
  File "./build.py", line 59, in <module>
    build(sys.argv[2])
  File "./build.py", line 26, in build
    use_opts = OPTS % (InputMethod[imname], use_path)
KeyError: ''

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

**Comment by xcodebuild** [comment]
It looks like you are using `brew install fcitx-remote-for-osx --with-input-method=" "`... `brew install fcitx-remote-for-osx --with-input-method=sogou-pinyin` works for me well.

BTW, after `0.1.0` we suggest using 

```
brew install fcitx-remote-for-osx
```

directly and set hot key for it as `README`.

**Comment by beeender** [comment]
`brew install fcitx-remote-for-osx --with-input-method=sogou-pinyin` still doesn't work.

But `brew install fcitx-remote-for-osx --with-input-method=sogou-pinyin` works. So never mind!
